### ISSUE TITLE
Rule proposal: alt text max length

### ISSUE THREAD

**Issue by lencioni** [jsx-eslint/eslint-plugin-jsx-a11y#264]
Some screen readers will not read alt text if it is too long, or they will break it up in confusing ways. It would be nice to have a rule to help prevent this. I've seen different recommendations, usually somewhere around 100 – 150 characters.

**Comment by evcohen** [comment]
[This](https://www.washington.edu/accessit/print.html?ID=1257) may be a little outdated, but it says JAWS partitions it at 125 characters. We can make that default

**Comment by jessebeach** [comment]
This is probably going to be difficult to test with lint. I'd imagine the alt attribute value will be assigned via variable in most cases. We'll probably not end up with many cases where this rule would apply.

**Comment by ljharb** [comment]
The rule, however, would be q good basis for a propType/flow type that did a runtime check

**Comment by evcohen** [comment]
@jessebeach we can make sure to only test for literal string values and can include in the `alt-text` rule. it couldn't hurt and could help people working on static sites.

**Comment by jessebeach** [comment]
> it could help people working on static sites.

Fair point.

**Comment by ljharb** [comment]
https://yatil.net/blog/there-is-no-character-limit-for-alt-text seems to suggest that this is a myth, or at least outdated advice. Perhaps we don't need a rule after all? (credit to @uncommon-type)

**Comment by BenDMyers** [comment]
Yeah, from what I can tell from resources like Eric Eggert's blogpost, linked by @ljharb above, if screenreaders ever had hard limits on alt text length, they're now purely historical. Resourcess you'll find on the subject are either outdated/sourcing from outdated sources, or they're trying to establish standardized best practices for their own organization. Alt text _should_ be kept concise - since, as has been noted, you can't pause alt text or rewind within alt text if you missed something: you have to start the alt text all over. So longer alt text can be pose a big usability problem, but not really a technical problem. But what "concise" means is image-dependent.

As it stands, WCAG for instance does not prescribe or even recommend any cap on alt text length, and based on [this ongoing thread](https://github.com/w3c/wcag/issues/2126), they're unlikely to. This is largely because HTML doesn't really have a robust way for supplying both shorter-form and longer-form descriptions, but they also cite concerns like internationalization which makes character limits a poor litmus test for verbosity or amount of information.

I'd find it really, really tough to recommend any particular character limits, especially if WCAG isn't.

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks @BenDMyers! I'll go ahead and close #834.
