### ISSUE TITLE
custom rule - how?

### ISSUE THREAD

**Issue by Felicia5** [jsx-eslint/eslint-plugin-jsx-a11y#772]
Hi,
I am trying to add a custom rule using the logic of heading-has-content rule. But instead of headings I am looking for div elements. Also, in the util hasAccessibleChild I am not only looking for any text but a text that is equal to "apply". 

#My questions:
1. I don't know how to handle these errors. Can you suggest some solutions?
    I generated the rule files using the create-rule.md file. I added my changes to the rule and rule-test files. I run npm test and receive these errors: 
    
    ![image](https://user-images.githubusercontent.com/13880509/107732476-580b0480-6cf0-11eb-83f9-a84f7a727335.png)

***Do you have a further guide on these below?***

    2. How do I test if the rule and the rule-test works as I want it to? 
      I have read the [eslint documentation](https://eslint.org/docs/developer-guide/unit-tests) but I couldn't find a solution. 

  3. Without merging my rule to the master branch, how do I add my custom  jsx-eslint /eslint-plugin-jsx-a11y plugin to test my code against the my new custom rule when I develop a new website?

here is my custom rule:
https://github.com/Felicia5/eslint-plugin-jsx-a11y/blob/first-rule-button/src/rules/first-rule-button.js

**Comment by ljharb** [comment]
Hmm - I haven't actually used that script; it was last touched 4 years ago. It's highly likely that it's out of date.

The error looks like it's coming from `flow` itself - what code are you running it on?

**Comment by Felicia5** [comment]
I got this error right after I :

1. run npm run create -- myrule --author="Felicia Kovacs" --description="Enforce use of button elements to display apply text"  - this is the command defined in the : https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/scripts/create-rule.md
2. added code to files: rule, rule-test and hasAccessibleChildApply.js util
3.  run npm test within int-plugin-jsx-a11y folder I forked and cloned on my local desktop. 

Any idea how I can get rid of the error message coming from flow?

**Comment by ljharb** [comment]
Can you make a branch on your fork, and post the link here? I'll clone it locally and try it out.

**Comment by Felicia5** [comment]
here it is: https://github.com/Felicia5/eslint-plugin-jsx-a11y/tree/felicia-rule

**Comment by Felicia5** [comment]
These are the steps I have done after forking:

used git clone https://github.com/Felicia5/eslint-plugin-jsx-a11y.git 
cd eslint-plugin-jsx-a11y
git remote add upstream https://github.com/jsx-eslint/eslint-plugin-jsx-a11y.git 
git checkout -b "felicia-rule"
git commit -m "cloned repo locally"
git push
git push --set-upstream origin felicia-rule
npm install
npm run create -- myrule --author="Felicia Kovacs" --description="Enforce use of button elements to display apply text" 


npm test
![image](https://user-images.githubusercontent.com/13880509/108264558-988ad800-715f-11eb-827d-b72c12fc1c7e.png)


git add .
git commit -m "generated rule files"
git push

![image](https://user-images.githubusercontent.com/13880509/108264528-8f9a0680-715f-11eb-95d6-d4ab2e3e5932.png)


I added my changes 

npm test
![image](https://user-images.githubusercontent.com/13880509/108264499-86109e80-715f-11eb-9872-9cf75b6f2818.png)

![image](https://user-images.githubusercontent.com/13880509/108264482-814bea80-715f-11eb-9af6-c67fc9f49c97.png)


git add .
git commit -m "added my changes to rule, rule-test and hasAccessibleChildMyrule util file."
git push
![image](https://user-images.githubusercontent.com/13880509/108264443-71cca180-715f-11eb-9848-90c52b2156e4.png)

**Comment by ljharb** [comment]
Go for it!

**Comment by V2dha** [comment]
The flowconfig error i.e. `if [ ! -e ./.flowconfig ]; then echo \"Could not find .flowconfig\"; else flow; test $? -eq 0 -o $? -eq 2; fi` is mentioned in the [Issue 855](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/855) and has been fixed in the latest commits. So upon replicating the new rule onto the latest commit I am no longer getting the above errors. 
But I am encountering the following errors which are related to import declarations in module.

```
 10:1   error  Cannot use import declarations in modules that export 
using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports
  11:1   error  Cannot use import declarations in modules that export 
using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports
  12:1   error  Cannot use import declarations in modules that export 
using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports
  12:32  error  Unable to resolve path to module '../util/hasAccessibleChildMyrule'                                                  import/no-unresolved
  12:32  error  Missing file extension for "../util/hasAccessibleChildMyrule"                                                        import/extensions
  13:1   error  Cannot use import declarations in modules that export using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports

✖ 6 problems (6 errors, 0 warnings)
```

**Comment by V2dha** [comment]
` 12:32  error  Unable to resolve path to module '../util/hasAccessibleChildMyrule'                                                  import/no-unresolved
  12:32  error  Missing file extension for "../util/hasAccessibleChildMyrule" ` these errors were due to wrong file name, it is `../util/hasAccessibleChild`. 
and `Cannot use import declarations in modules that export 
using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports` errors were due to the `module.exports` instead of `export default` that was mentioned in the boilerplate which is not updated yet. Upon fixing these errors the tests are now running out of which 12 are failing as mentioned below due to the following error `"Apply text must be in button elements and not div elements."`  which is I guess the custom rule is trying to achieve.

`Test Suites: 1 failed, 60 passed, 61 total
Tests:       12 failed, 15384 passed, 15396 total
Snapshots:   0 total
Time:        29.889s
Ran all test suites matching /__tests__\/__util__\/axeMapping.js|__tests__\/__util__\/parserOptionsMapper.js|__tests__\/__util__\/ruleOptionsMapperFactory.js|__tests__\/src\/rules|__tests__\/src\/util/i.`

**Comment by ljharb** [comment]
I'm going to close this; please file a new issue if anyone's still having trouble.
