### ISSUE TITLE
This repo is probably in violation of the MPL license due to it's inclusion of axe-core

### ISSUE THREAD

**Issue by james-bw** [jsx-eslint/eslint-plugin-jsx-a11y#860]
```
$ npm list axe-core
some_repo@ C:\Users\some\directory
└─┬ eslint-plugin-jsx-a11y@6.5.1
  └── axe-core@4.4.1
```

https://github.com/dequelabs/axe-core/blob/develop/package.json:

```
...
"license": "MPL-2.0",
...
```

https://www.mozilla.org/en-US/MPL/2.0/

3.1. Distribution of Source Form
All distribution of Covered Software in Source Code Form, including any Modifications that You create or to which You contribute, must be under the terms of this License. You must inform recipients that the Source Code Form of the Covered Software is governed by the terms of this License, and how they can obtain a copy of this License. You may not attempt to alter or restrict the recipients’ rights in the Source Code Form.

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/package.json:

```
...
  "license": "MIT",
...
```

Ideally an alternative proper open source library would be used.

**Comment by ljharb** [comment]
This repo does not include axe-core, it depends on it, and as such, axe-core's license is _irrelevant_ to anyone but the final end user.

Licenses of dependencies only matter when they're bundled into the distribution, which doesn't apply to virtually any npm packages. Feel free to consult an IP attorney if you disagree.

**Comment by james-bw** [comment]
Obviously I'm not going to consult an IP attorney with all that related cost for something like this, I'm just going to drop using eslint-plugin-jsx-a11y in any project I ever work on for the avoidance of risk. 

Of 1600 open source libraries in my dependency tree, axe-core is the **only one** that doesn't use a nice copyleft type license like MIT or BSD. Just thought I'd raise it for your awareness.

**Comment by ljharb** [comment]
I would encourage you to file it on axe-core; perhaps they'll consider relicensing to MIT.

However, again, there's zero risk unless you are redistributing axe-core. This plugin does not do so; it merely distributes instructions for npm to download it directly.

**Comment by mjsalinger** [comment]
@ljharb This is not accurate.  Any *dependency* of a project needs to adhere to the license terms of that project.  `node_modules` constitutes *static linking* because the code is loaded at build time and is included in the source executable when `node` is run or is included as the output of a react build, for example, even in minimized form.   This is in violation of copy-left licenses, which prohibit static linking.  

Dynamic linking is allowed - when the dependency is an executable that is *not* loaded at build time and is not part of the memory space when the application starts (for example, a command line utility or a database server).  

And yes, I have talked to multiple IP attourneys about this as we were crafting my company's OSS policy.

**Comment by ljharb** [comment]
Licensing impacts distribution only. We do not distribute axe-core. I’m not sure what to tell you - perhaps your attorneys don’t understand how the JavaScript ecosystem works since they’re talking about “linking”, which simply isn’t a concept that applies.

**Comment by dylanb** [comment]
All that MPL says (paraphrasing here) is that if you modify our code, you have to publish the derivative work under MPL2, so if you don't plan to modify our code it shouldn't be a problem. This repo does not modify the axe-core code so there is no violation here.

**Comment by mjsalinger** [comment]
@dylanb - yes you're right.  I took a deeper look at the MPL in particular.  It had been flagged by a license scanning tool we use because it does include minimal copy-left provisions, but upon reading it (and verifying with our lawyers), it appears that we are in the clear as we won't be modifying it (as opposed to GPL libraries)...

**Comment by PredokMiF** [comment]
I faced a similar problem. In addition, there is clause 3.2 of the MLP 2.0 license, which requires disclosure of source codes.

To build my project, this library is installed and appears in node_modules, which my lawyer considers unacceptable.
The library is only used for testing, which means you can transfer this library to DevDependency, then the library will not be downloaded.
