### ISSUE TITLE
[no-noninteractive-element-interactions] <label/> should be able to accept event handlers

### ISSUE THREAD

**Issue by sangikhan29** [jsx-eslint/eslint-plugin-jsx-a11y#934]
Similarly to the [previous issue](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/932), but on a different rule, `no-noninteractive-element-interactions` should allow `<label/>` to accept event handlers like `onClick`. In [this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#examples), `<label/>` is used to shift focus to the `<input/>` upon click. So `<label/>` is not a non-interactive element.

Sometimes adding custom `onClick` is needed to support logging etc.

**Comment by sangikhan29** [comment]
Hi @jessebeach, sorry to ping you right after [dialog](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/932) is resolved. But is there any update on this as well? Please let us know if there's something we can do to help!

**Comment by jessebeach** [comment]
Hello again @sangikhan29!

> Sometimes adding custom onClick is needed to support logging etc.

This isn't something that this project can support. Any element could conceivably have a click handler added to it to support logging. I recommend either adding a suppression comment to suppress the warning or capture events for logging at the document rather than at each individual element. 

Click handlers should be added to the control elements themselves, not the labels that describe them. If a label contains a control element, it will become clickable...this is something the browser client does automatically in this case.

**Comment by sangikhan29** [comment]
Hi @jessebeach, thanks for looking into this! 🙏  I'll probably go ahead with suppressing existing ones but still enable to rule so that we can avoid similar cases in the future.
